base_config:
  - ../../ffhq/img2plane.yaml
  - ../../ffhq/base.yaml
  
not_save_modules: ['criterion_lpips', 'eg3d_model']
ds_name: FFHQ # FFHQ | FFHQ_and_TH1KH_512 # 发现引入视频数据会导致画质变差
task_cls: tasks.os_avatar.img2plane_task.OSAvatarImg2PlaneTask

batch_size: 1
normalize_radius: false

optimizer_adam_beta1_g: 0.
optimizer_adam_beta2_g: 0.99
optimizer_adam_beta1_d: 0.
optimizer_adam_beta2_d: 0.99

lambda_mse_depth: 0.

start_adv_iters: 30000
lr_g: 0.0001
lr_d: 0.0002

img2plane_backbone_mode: composite # composite | segformer

ffhq_disc_inp_mode: eg3d_gen
use_th1kh_disc: false # enable only when ds_name == FFHQ_and_TH1KH_512
lpips_mode: vgg19_v2 # vgg19 | vgg16 | alex | vgg19_v2

enable_rescale_plane_regulation: true
img2plane_backbone_scale: standard # standard | large
update_on_th1kh_samples: false

init_from_ckpt: 'checkpoints/0823_img2plane/img2plane'

triplane_feature_type: triplane # triplane # trigrid # trigrid_v2
triplane_depth: 1 # now use 3
triplane_hid_dim: 32 # 32
clip_grad_norm: 1.0

use_th1kh_mv_adv: false
torch_compile: true
use_mse: false